# SPDX-FileCopyrightText: 2019 Libor Polcak <polcak@fit.vutbr.cz>
# SPDX-License-Identifier: GPL-3.0-or-later

defaults:
  -
    scope:
       path: ""
    values:
      title: JavaScript Restrictor
      layout: default
